services:
  - type: web
    name: mental-health-survey-viz
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
